#!/usr/bin/python

import os
import sys

def main(input_video):
    os.system(
        "ffmpeg -i " + input_video + " "
        "-c:v copy "
        "-c:a aac "
        "-b:a 128k "
        "-start_number 0 "
        "-hls_time 10 "
        "-hls_list_size 0 "
        "-f hls "
        "playlist.m3u8"
    )
    os.system("mkdir -p static/video")
    os.system("mv *.ts playlist.m3u8 static/video/")


if __name__ == "__main__":
    main(sys.argv[1])
